name: Third Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Empty files
        run: |
          ls -a
      - uses: actions/checkout@v4
      - name: Show files
        run: |
          ls -a
