name: Third Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Empty files
        run: |
          ls -a
      #   - uses: actions/checkout@v4
      - name: Show files
        run: |
          git init
          git remote add origin https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}github.com/$GITHUB_REPOSITORY.git
          git fetch origin
          git checkout master
      - name: List files
        run: ls -a
